language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:		
  - composer install

script:
  - phpunit

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - master
